org: jrb331
app: api
service: api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 10

plugins:
  - serverless-offline

functions:
  api:
    handler: handlers/index.handler
    events:
      - http:
          path: /
          method: get
  authorize:
    handler: handlers/authorize.authorize
    events:
      - http:
          path: authorize
          method: get